apiVersion: batch/v1
kind: Job
metadata:
  name: pythonchallenge
spec:
  template:
    spec:
      containers:
      - name: pythonchallenge
        image: myawesomeproject.jfrog.io/default-docker-local/ory:1.0.1
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
  backoffLimit: 4