apiVersion: batch/v1
kind: Job
metadata:
  name: pythonchallenge
spec:
  template:
    spec:
      containers:
      - name: pythonchallenge
        image: PRIVATE-REPO-PATH-AND-IMAGE-NAME-WITH-TAG
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never
  backoffLimit: 4
