apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteWF3ZXNvbWVwcm9qZWN0Lmpmcm9nLmlvIjp7InVzZXJuYW1lIjoibXlhd2Vzb21ldXNlciIsInBhc3N3b3JkIjoiQWRtaW4xMjM0ISIsImVtYWlsIjoib3J5c0BqZnJvZy5jb20iLCJhdXRoIjoiYlhsaGQyVnpiMjFsZFhObGNqcEJaRzFwYmpFeU16UWgifX19
type: kubernetes.io/dockerconfigjson